get_map:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: yarbo_local

get_obstacles:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: yarbo_local
    run_id:
      required: false
      selector:
        text:

start_plan:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: yarbo_local
    plan:
      required: true
      example: "east lawn plan"
      selector:
        text:
